' ******************************************************************************
' swxJRNL.swj - journal recorded on 06/10/24 by PC
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Assemble3.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.3923530913183737034, 0.08163193509327827668, -0.1602362112928972238, -0.03061659966392227261, 0.09637572381811887468

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "Assemble3.SLDASM"
swApp.ActivateDoc2 "FuselageNew.SLDPRT", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Close Document
swPart = Nothing
Set Part = Nothing
swApp.CloseDoc "FuselageNew.SLDPRT"
swApp.ActivateDoc2 "Сборка.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2

' Named View
Part.ShowNamedView2 "*Сверху", 5
Part.ViewZoomtofit2
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01089869698106593794, -0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01816449496844322817, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05449348490532968797, 0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05449348490532968797, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05449348490532968797, 0.09892212161822554195
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.06175928289270697646, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05449348490532968797, 0.1065315155888582749
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.04722768691795239254, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02543029295582052013, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.05086058591164104026, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02179739396213187588, 0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02179739396213187588, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02543029295582052013, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01816449496844322817, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.03632898993688645634, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01089869698106593794, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01089869698106593794, 0.02282818191189820226
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.02179739396213187588, 0.07609393970632734316
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01453159597475458392, 0.02282818191189820226
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007265797987377291961, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01453159597475458392, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01816449496844322817, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01089869698106593794, 0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01089869698106593794, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.007265797987377291961, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.01816449496844322817, 0.08370333367696007609
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003632898993688645981, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003632898993688645981, 0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter -0.003632898993688645981, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.07609393970632734316
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, 0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, 0.07609393970632734316
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, 0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.09892212161822554195
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02179739396213187588, 0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, 0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02179739396213187588, 0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, 0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.01521878794126546933
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, 0.01521878794126546933
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0.01521878794126546933
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, 0.02282818191189820226
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, 0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, 0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02179739396213187588, 0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, -0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02179739396213187588, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02906319194950916784, -0.01521878794126546933
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02906319194950916784, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02906319194950916784, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02179739396213187588, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.04722768691795239254, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01816449496844322817, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.02543029295582052013, -0.09892212161822554195
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01453159597475458392, -0.1293596975007564875
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.01089869698106593794, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06848454573569461024
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.05326575779442913744
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.06087515176506187731
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.04565636382379640451
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.02282818191189820226
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.07609393970632734316
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.03804696985316367158
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.007265797987377291961, -0.02282818191189820226
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.03043757588253093865
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0.003632898993688645981, -0.007609393970632734663
Set myModelView = Part.ActiveView
myModelView.RotateAboutCenter 0, -0.01521878794126546933

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.02282818191189820226, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.02282818191189820226, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.02282818191189820226, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, 0, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.01521878794126546933, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01453159597475458392, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, -0.02282818191189820226, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, -0.007609393970632734663, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, 0, 0.01157607740401545016, 0.05739360829315387491, 0.01650313714907269969

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.007609393970632734663, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.03804696985316367158, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.01521878794126546933, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.03043757588253093865, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.06848454573569461024, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.02282818191189820226, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutAxis 0.02282818191189820226, -0.01350020753663727646, 0.1232552859863886852, 0.05493878884453806677, 1, 0, 0

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03996188893057510405, 0.1445784854420219534, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, 0.05326575779442913744, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, 0.07609393970632734316, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, 0.07609393970632734316, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, 0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02906319194950916784, 0.07609393970632734316, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02179739396213187588, 0.08370333367696007609, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01453159597475458392, 0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, 0.1065315155888582749, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01453159597475458392, 0.04565636382379640451, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01816449496844322817, 0.04565636382379640451, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01453159597475458392, 0.06087515176506187731, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01089869698106593794, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01453159597475458392, 0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003632898993688645981, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.007265797987377291961, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04565636382379640451, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01453159597475458392, 0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01453159597475458392, 0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, 0, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01816449496844322817, -0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.05326575779442913744, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.07609393970632734316, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.05326575779442913744, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.04565636382379640451, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.05326575779442913744, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.07609393970632734316, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.04565636382379640451, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.03043757588253093865, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05326575779442913744, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.03804696985316367158, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.01521878794126546933, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.02282818191189820226, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, -0.0007647515651996172892, 0.0933590310471288376, -0.05514509227970165739

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0.02282818191189820226, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01453159597475458392, 0.01521878794126546933, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0.01521878794126546933, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01816449496844322817, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01816449496844322817, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.01521878794126546933, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, 0, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01089869698106593794, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.007609393970632734663, 0.1630745765759797905, 0.1185875467241146453, -0.05670000000014852048

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.03043757588253093865, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.03043757588253093865, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003632898993688645981, -0.05326575779442913744, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.06848454573569461024, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1065315155888582749, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04565636382379640451, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03043757588253093865, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03043757588253093865, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.007265797987377291961, -0.007609393970632734663, 0.198600000000055843, 0.1284665640035882461, -0.03789470602424671597

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "Сборка.SLDASM"
