' ******************************************************************************
' swxJRNL.swj - journal recorded on 07/04/24 by PC
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Сборка_Copy.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized

' Redraw
Part.GraphicsRedraw2

' Save
Dim swErrors As Long
Dim swWarnings As Long
boolstatus = Part.Save3(1, swErrors, swWarnings)

' Close Document
swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "Сборка_Copy.SLDASM"

' Open
Set Part = swApp.OpenDoc6("C:\Users\PC\Education\2024\FAKI_SKAT2024\Manufacturing\Model\Модель\ТекущаяСборка\Сборка_Copy.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
swApp.ActivateDoc2 "Сборка_Copy.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07338148094454989556, 0.02282818191189820226, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03144920611909281238, 0.01521878794126546933, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02446049364818329852, 0.05326575779442913744, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03494356235454756238, 0.04565636382379640451, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03494356235454756238, 0.03804696985316367158, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02795484988363805198, 0.04565636382379640451, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03843791859000232625, 0.06087515176506187731, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, 0.04565636382379640451, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01747178117727378119, 0.03804696985316367158, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02446049364818329852, 0.04565636382379640451, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02446049364818329852, 0.03804696985316367158, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, 0.03043757588253093865, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, 0.03043757588253093865, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003494356235454756498, 0.007609393970632734663, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, 0.007609393970632734663, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, 0.04565636382379640451, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02282818191189820226, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003494356235454756498, 0.01521878794126546933, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, 0.02282818191189820226, 0.110007656096819062, 0.1370492823669451354, 0.3169203703301946007

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.04193227482545708318, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003494356235454756498, -0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003494356235454756498, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01747178117727378119, -0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.02282818191189820226, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02096613741272854159, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03494356235454756238, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02096613741272854159, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, -0.03043757588253093865, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03144920611909281238, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02446049364818329852, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01747178117727378119, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.03043757588253093865, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, -0.05326575779442913744, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, -0.03043757588253093865, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01747178117727378119, -0.06087515176506187731, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, -0.02282818191189820226, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02446049364818329852, -0.09892212161822554195, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01397742494181902599, -0.06848454573569461024, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.003494356235454756498, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.006988712470909512996, -0.09131272764759280902, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01048306870636427079, -0.02282818191189820226, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.05326575779442913744, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03804696985316367158, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04565636382379640451, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02282818191189820226, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, -0.02282818191189820226, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01048306870636427079, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01747178117727378119, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.006988712470909512996, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01747178117727378119, 0, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01048306870636427079, 0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01747178117727378119, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02795484988363805198, 0.03043757588253093865, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01048306870636427079, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01048306870636427079, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01747178117727378119, 0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01747178117727378119, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.003494356235454756498, 0.01521878794126546933, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01397742494181902599, -0.007609393970632734663, 0.03944164957738394151, 0.03521455958519936758, 0.03534700731449902378

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Close Document
Set swAssembly = Nothing
Set Part = Nothing
swApp.CloseDoc "Сборка_Copy.SLDASM"
swApp.ActivateDoc2 "Сборка_Copy.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
Set Part = swApp.ActiveDoc
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 0
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
Set myModelView = Part.ActiveView
myModelView.FrameState = swWindowState_e.swWindowMaximized
swApp.ExitApp
End Sub
